### ISSUE TITLE
Proposta modifiche al testo - Compatibilità Firefox

### ISSUE THREAD

**Issue by iusondemand** [ondata/vaccinipertutti#11]
Grande lavoro.
Il testo (ottimo) mi sembra molto complesso, pur completo.

Cambierei "Termine previsto della campagna vaccinale in Italia contro Sars-CoV-2." in

"[corsivo]L'Italia sarà vaccinata il:
[linea vuota piu' alta]
             [grande come ora, non corsivo]21 giugno 2024 (senza mettere il giorno della settimana, non e' utile).
[linea vuota piu' alta]
[corsivo]vaccinando con 2 dosi il 70% della popolazione, all'attuale ritmo.
Spiegazione:
......
"
ps: con Firefox gli input perdono la formattazione.

**Comment by aborruso** [comment]
Firefox

![image](https://user-images.githubusercontent.com/30607/105156435-21d0cf80-5b0c-11eb-98c0-898ca63e872f.png)

**Comment by jenkin** [comment]
Potete verificare se il problema con Firefox è ancora presente?

Se sì, aprirei una nuova issue.

@iusondemand grazie della proposta, ma mi sembra un testo un po' troppo strutturato, l'idea di fondo è che sia discorsivo, come un articolo di giornale (vedi le faq nel nuovo readme).

Specificare il giorno della settimana non è un caso, è un tentativo di indurre un senso di straniamento nel lettore: la data è anni avanti, ma ti dico pure il giorno della settimana, che è la tipica domanda che uno si fa quando pensa alle feste o a scadenze importanti: esempio "in che giorno cade quest'anno il primo maggio?"

Naturalmente la speranza è che le cose si sistemino e che quella data possa tornare a segnare un giorno di quest'anno e allora sì che ci sarà da festeggiare... :)

**Comment by rosamarco** [comment]
Non sono sicuro che sia la soluzione migliore, ma può essere risolto aggiungendo 
```css
input[type=number] {
    width: 5ch;
}
```
in App.css

**Comment by aborruso** [comment]
> Potete verificare se il problema con Firefox è ancora presente?

C'è già una issue dedicata https://github.com/ondata/vaccinipertutti/issues/14#issuecomment-804287386
