### ISSUE TITLE
confronto internazionale

### ISSUE THREAD

**Issue by palmierieugenio** [ondata/vaccinipertutti#16]
Proporrei l'aggiunta di un confronto internazionale (magari in una pagina separata per non appesantire l'infografica). Le preoccupazioni sull'equità ed i tempi dell'accesso al vaccino sembrano ancora maggiori se uno guarda con una prospettiva internazionale e sembra un argomento coperto molto poco dai media.

Potrebbe essere interessante in particolare mostrare la percentuale (rispetto alla popolazione) di somministrazioni e la percentuale di vaccini completi (doppia dose), oltre che plot bivariati su variabili di interesse, come Pil, Pil pro capite e variabili sulla gravità del virus (stime di morti covid e stime di eccesso di mortalità) o altre variabili che vi vengono in mente (al posto di punti, si possono usare etichette coi nomi dei paesi, magari con colori separati per continente).

Sarebbe anche interessante mostrare informazioni sul costo del vaccino per paese e mostrare informazioni sulle donazioni internazionali di vaccini, possibilmente con informazioni sui fondi dei donatori e vaccini ricevuti dai beneficiari.

Riguardo le fonti, mi erano stati segnalati questi link:

https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations
https://www.bbc.com/news/business-55170756

Ma non sembrano affatto sufficienti per mettere a punto la mia proposta, servirebbe una ricerca ulteriore.

PS: Ovviamente mi rendo conto che è molto più complesso accedere a fonti sull'argomento ed è di più difficile implementazione. Scusate se ritenete la proposta offtopic, effettivamente è la proposta di un'estensione del vostro progetto, che al momento ha una prospettiva nazionale. Si tratta di un progetto molto ambizioso, che richiederebbe molto lavoro, ma penso che siate una delle poche organizzazioni in Italia che potrebbe effettivamente riuscirci.

**Comment by jenkin** [comment]
@palmierieugenio scusa il ritardo della risposta, l'idea è interessante, ma ritengo che esca dallo scopo di questa applicazione. Ce ne sono altre che confrontano la situazione italiana con quelle degli altri paesi. Grazie comunque del contributo!
