### ISSUE TITLE
File piano vaccinazioni più aggiornato

### ISSUE THREAD

**Issue by aborruso** [ondata/vaccinipertutti#17]
Sul sito del Ministero della salute, ce ne è uno al 2 gennaio 2021

<https://www.trovanorme.salute.gov.it/norme/renderNormsanPdf?anno=2021&codLeg=78657&parte=1%20&serie=null>

Valutare se è necessario modificare qualche "paletto" numerico.

**Comment by jenkin** [comment]
Superata da #23
