### ISSUE TITLE
¡¡¡ Valori italiani non corretti !!!

### ISSUE THREAD

**Issue by jenkin** [ondata/vaccinipertutti#18]
L'[ultimo aggiornamento dei dati ufficiali](https://github.com/italia/covid19-opendata-vaccini/issues/70) ha introdotto senza preavviso una *breaking change* che impedisce la corretta visualizzazione dei dati italiani.

I dati regionali sono invece corretti.

**Comment by aborruso** [comment]
Ale non so aiutarti nei modi che sarebbero utili a te (immagino tu faccia robe javascript live).

Io ci posso mettere uno script che crea l'output secondo lo schema desiderato, a partire dal nuovo schema di input. Insomma sciocchezze che sai fare molto meglio di me.

**Comment by jenkin** [comment]
Grazie, ci penso io, sistemo domani... :)

**Comment by vvzen** [comment]
Screenshot per memoria futura: to NaN or not to NaN :D 

<img width="1028" alt="Screenshot 2021-01-31 at 23 58 54" src="https://user-images.githubusercontent.com/10340139/106402377-1beac080-6421-11eb-9d6f-e37c7bab14e8.png">

Scherzi a parte, bel progetto! Sono curioso di sapere come siamo messi. Grazie per averlo reso open-source! :)

**Comment by LucaZeta** [comment]
> immagino tu faccia robe javascript live

Le poche riche js necessarie per ordinare l'array per data_somministrazione e per area:
`        data.data.sort(function(a, b) {
            dataA = new Date(a.data_somministrazione);
            dataB = new Date(b.data_somministrazione);
            if(dataA.getTime() > dataB.getTime()) return 1;
            if(dataA.getTime() < dataB.getTime()) return -1;
            if(a.area > b.area) return 1;
            if(a.area < b.area) return -1;
            return 0;
        });
`

**Comment by aborruso** [comment]
> Le poche riche js necessarie per ordinare l'array per data_somministrazione e per area:

Luca grazie. Immagino sia facile. Ma non è il mio ambiente e qui ero poco utile.

@jenkin è cintura nera per fortuna.

**Comment by jenkin** [comment]
@LucaZeta l'ordinamento inverso per data avviene qui subito dopo il caricamento dei dati: https://github.com/ondata/vaccinipertutti/blob/main/src/App.js#L148 (uso una [utility di d3js](https://observablehq.com/@d3/d3-ascending)). L'ordinamento per area invece non serve, perché le aree sono solo chiavi di filtro. Grazie comunque!

**Comment by LucaZeta** [comment]
> ordinamento inverso per data avviene qui subito dopo il caricamento dei dati

Interessante, gli dedicherò un po' di tempo alla ricerca di spunti che sono certo non mancheranno.
