### ISSUE TITLE
Immunizzati e vaccinati

### ISSUE THREAD

**Issue by giamp63** [ondata/vaccinipertutti#19]
Occorrere considerare il coefficiente di immunizzazione medio dei vaccini.
Per ottenere L’ immunizzazione del 70% della popolazione occorre vaccinare ben più del 70%.
Se ad esempio un vaccino garantisce una percentuale di immunizzati pari a 92, occorrerà vaccinare almeno il 76% per ottenere il 70% di immunizzati e quindi l’immunità cosiddetta 'di gregge'. 
Saluti
G.

**Comment by jenkin** [comment]
Grazie del contributo, hai ragione, ma ci sono due questioni importanti:

- nei dati rilasciati al momento è impossibile capire quante somministrazioni per ogni vaccino sono state fatte (in prima e seconda dose);

- l'obiettivo dichiarato e che noi prendiamo in considerazione è sulla popolazione vaccinata (una percentuale del totale), non sulla stima di quella immunizzata.

In ogni caso puoi modificare liberamente quel 70%, portarlo per esempio a 76% e vedere che succede... :)
