### ISSUE TITLE
idea: aggiungere anche la pagina che dà conto dei numeri rispetto agli scenari ad oggi dichiarati

### ISSUE THREAD

**Issue by aborruso** [ondata/vaccinipertutti#2]
Ad oggi sappiamo che l'obiettivo è vaccinare il paese, diciamo almeno l'80% della popolazione.

Però [qui](https://www.epicentro.iss.it/vaccini/covid-19-piano-vaccinazione) leggiamo pure:

> Il cronoprogramma stabilisce che gli appartenenti alle tre categorie a massima priorità siano coinvolti nel primo trimestre 2021: si tratta di 1,4 milioni di operatori sanitari, 570.000 tra personale e ospiti delle RSA e 4,4 milioni di anziani con più di 80 anni. Entro il secondo trimestre verrà coinvolta la fascia di età 60-79 anni (13,4 milioni) e le persone con almeno una patologia cronica (7,4 milioni). Tra il secondo e il terzo trimestre, con l'aumento delle dosi di vaccino disponibili, si passerà a vaccinare le altre categorie tra cui gli appartenenti ai servizi essenziali (insegnanti e personale scolastico, forze dell'ordine, personale delle carceri e di comunità, ecc), infine nel quarto trimestre è prevista l’estensione al resto della popolazione.

Si possono estrarre delle milestone e preparare - probabilmente meglio un'altra pagina - che tiene conto di questi punti:

- entro il 2020-03-31 dovranno essere vaccinati (doppio somministrati) 5.8 milioni di persone
  - 1,4 milioni di operatori sanitari, 570.000 tra personale e ospiti delle RSA
  - 4,4 milioni di anziani con più di 80 anni
- entro il 2020-06-31 20.8 milioni di persone
  - la fascia di età 60-79 anni (13,4 milioni) 
  - le persone con almeno una patologia cronica (7,4 milioni)

Con questi paletti la nuova pagina potrebbe essere:

> Il cronoprogramma (mettendo il link a pagina ISS) inoltre prevede di vaccinare al 31 marzo 2020 5.8 milioni di persone. Al ritmo corrente ci si arriverà al ...., con un ritardo quindi di ...

Si potrebbe scrivere una frase che tenga conto delle due milestone o inserire la seconda dal primo aprile.

**Comment by nelsonmau** [comment]
secondo me se non c'è questa informazione è più un bug che non un miglioramento (l'informazione sarebbe incompleta...)

**Comment by jenkin** [comment]
Continueremo per sempre ad avere definizioni radicalmente diverse di bug e feature... :O

**Comment by jenkin** [comment]
Propongo di aggiungere una frase al testo attuale con due alternative:

- "Il ritmo attuale è in linea con il prossimo obiettivo di vaccinare TOT persone (TIPOLOGIE) entro il MESE ANNO"
- "Il ritmo attuale dovrebbe aumentare del TOT% per raggiungere il prossimo obiettivo di vaccinare TOT persone (TIPOLOGIE) entro il MESE ANNO"

Personalmente tralascerei la specifica delle tipologie per tenere breve il testo.

La frase aggiuntiva si riferisce solo all'obiettivo futuro più vicino.

Il TOT% è calcolato come (ritmo previsto - ritmo attuale) / ritmo previsto. Ritmo è somministrazioni al giorno.

**Comment by jenkin** [comment]
@aborruso secondo te come si conciliano gli scenari dell'ISS che hai messo tu con questi di cui parla il Sole24Ore? https://lab24.ilsole24ore.com/numeri-vaccini-italia-mondo/

![Screenshot_20210118_174123](https://user-images.githubusercontent.com/426495/104942409-b4f6f180-59b4-11eb-8770-9fbee6ab58f0.png)

**Comment by aborruso** [comment]
Caro @jenkin il sole ha usato questo documento http://www.salute.gov.it/imgs/C_17_pubblicazioni_2986_allegato.pdf

In questo ci sono gli stessi numeri delle due fasi, che ho messo nel JSON.

La prima fase corrisponde (sia nel mio JSON, che in questo documento) a circa 6.400.000 persone. Che non sono il 5% né dell'intera popolazione, né del 70%. E nel grafico del sole è a 5.

Ed è a 5 anche in questo PDF. Per me non ha molto senso. Ma i numeri qui sono confermati e con qualche dettaglio in più, che potremmo riportare nel JSON

![image](https://user-images.githubusercontent.com/30607/104953704-30fa3500-59c7-11eb-8ba3-30dc82903c9c.png)

**Comment by jenkin** [comment]
Fatto, gli scenari sono qui: https://github.com/ondata/vaccinipertutti-data/blob/main/campaign-milestones.json
