### ISSUE TITLE
Parametrizzare l'url per Regione

### ISSUE THREAD

**Issue by nelsonmau** [ondata/vaccinipertutti#20]
ad esempio se metto quest'url `https://ondata.github.io/vaccinipertutti/?r=lombardia`

mi compare questo:
![2021 02 04-ondata github io](https://user-images.githubusercontent.com/1769578/106910711-c99bef00-6701-11eb-896f-b3457c06b8f6.png)

**Comment by aborruso** [comment]
È già così, con le vecchie sigle. Se cambi regione, cambia URL ed è un permalink https://ondata.github.io/vaccinipertutti/?area=LOM

Era la prima issue https://github.com/ondata/vaccinipertutti/issues/1#issue-784873309

**Comment by aborruso** [comment]
Ed è così con gli altri parametri https://ondata.github.io/vaccinipertutti/?area=LOM&targetMonth=7

**Comment by nelsonmau** [comment]
apperò
