### ISSUE TITLE
Problema sulle caselle di testo numeriche

### ISSUE THREAD

**Issue by malta895** [ondata/vaccinipertutti#21]
Le caselle di testo numeriche non fanno controlli sui limiti se il valore è inserito manualmente con la tastiera, senza utilizzare i bottoni di incremento e decremento, che invece rispettano i limiti. 
Ciò causa errori se si inseriscono numeri fuori dai limiti. 

Testato su Firefox 85.0.1 per Linux e Google Chrome 88.0.4324.150 per Linux, entrambi i browser presentano lo stesso problema.

![2021-02-10_23-23](https://user-images.githubusercontent.com/27235626/107580596-177b9000-6bf7-11eb-807f-0d063bc9f9e4.png)

**Comment by jenkin** [comment]
Grazie @malta895 , ho fatto il merge della tua PR, chiudo altre issue e poi pubblico. Grazie ancora!

**Comment by malta895** [comment]
Prego! Grazie a voi per il progetto molto utile!

**Comment by jenkin** [comment]
E grazie anche a @rosamarco per la PR! :)
