### ISSUE TITLE
Pubblicato nuovo documento piano vaccini

### ISSUE THREAD

**Issue by aborruso** [ondata/vaccinipertutti#23]
Il 13 marzo 2021 è stata data notizia in [questa pagina](http://www.governo.it/it/articolo/piano-la-campagna-vaccinale/16395), di un [nuovo documento di piano](http://www.governo.it/sites/governo.it/files/210313_Piano_Vaccinale_marzo_2021.pdf).

A una prima lettura, non emergono (per questa app) elementi forti.

Per punti:

- si vuole raggiungere almeno 500.000 somministrazioni giorno (entro il mese di aprile)
- 80% dei cittadini vaccinati entro settembre 2021

 

### Approvvigionamenti previsiti

![image](https://user-images.githubusercontent.com/30607/111062764-4c575d00-84ab-11eb-9a2c-039477846b1f.png)

### Stima somministrazioni e forniture

C'è questa immagine

![image](https://user-images.githubusercontent.com/30607/111062885-04850580-84ac-11eb-83f4-63a6e2e26a63.png)

Ho usato [WebPlotDigitizer](https://apps.automeris.io/wpd/) per estrarre i dati. Come immagine di estrazione ho usato [questa](https://i.imgur.com/Jy4vn9u.png).<br>
[Questo](https://github.com/ondata/vaccinipertutti/files/6136342/piano_vaccini_2021-03-13.zip) il file di progetto.

Qui i dati estratti: <https://docs.google.com/spreadsheets/d/1sFCWES1qLQ1AcmjLtaG2KuwSpPgS76hZuDpbNENPknk/edit?usp=sharing>

**Comment by jenkin** [comment]
Ottimo, grazie! Ma questo documento supera quello in #17, vero? In tal caso possiamo chiudere quella issue.

**Comment by jenkin** [comment]
@aborruso c'è da dire che non si capisce se questo nuovo piano supera il [precedente](https://www.epicentro.iss.it/vaccini/covid-19-piano-vaccinazione) oppure se lo integra...

> Il cronoprogramma stabilisce che gli appartenenti alle tre categorie a massima priorità siano coinvolti nel primo trimestre 2021: si tratta di 1,4 milioni di operatori sanitari, 570.000 tra personale e ospiti delle RSA e 4,4 milioni di anziani con più di 80 anni. Entro il secondo trimestre verrà coinvolta la fascia di età 60-79 anni (13,4 milioni) e le persone con almeno una patologia cronica (7,4 milioni). Tra il secondo e il terzo trimestre, con l'aumento delle dosi di vaccino disponibili, si passerà a vaccinare le altre categorie tra cui gli appartenenti ai servizi essenziali (insegnanti e personale scolastico, forze dell'ordine, personale delle carceri e di comunità, ecc), infine nel quarto trimestre è prevista l’estensione al resto della popolazione.

**Comment by jenkin** [comment]
Ok, per il momento ho [integrato le due fonti](https://github.com/ondata/vaccinipertutti-data/blob/main/campaign-milestones.json), aggiungendo gli obiettivi intermedi del nuovo piano a quelli del vecchio.

Ho anche aggiunto il supporto all'attributo `deprecated` per le milestone, così che se ci chiariranno i dubbi sarà facile _disabilitare_ le milestone non più valide.
