### ISSUE TITLE
Errore nel calcolo dei giorni

### ISSUE THREAD

**Issue by aborruso** [ondata/vaccinipertutti#25]
Ce l'hanno segnalato qui https://twitter.com/costantonio11/status/1371728587724840969

Ho appena testato oggi 16 marzo 2021 alle 9:00, e la data finale stimata è "Sabato 20 Agosto 2022".

Che nel testo viene riportato come "1 anni, 5 mesi e 5 giorni" da oggi. Invece sono "1 anni, 5 mesi e 4 giorni"

**Comment by jenkin** [comment]
Ho sostituito il calcolo fatto a mano con [una libreria](https://day.js.org/docs/en/durations/durations), il risultato è simile. Non saprei,  per ora ho aggiunto un `circa` nel testo, l'errore c'è ma rimane piccolo.
