### ISSUE TITLE
Mancato funzionamento su Safari

### ISSUE THREAD

**Issue by EliaTolin** [ondata/vaccinipertutti#26]
Ciao ! 
Sto tentando di aprire il sito da Safari ma purtroppo non riesco a visualizzare niente se non uno sfondo giallo.

La versione da me utilizzata è MacOS 11.2.3 (20D91).

A disposizione,
Elia.

**Comment by jenkin** [comment]
Il problema si è risolto da solo stamattina e non sono riuscito a riprodurlo, chissà! :)
