### ISSUE TITLE
Domani: previsto cambio schema dati di uno dei dataset

### ISSUE THREAD

**Issue by aborruso** [ondata/vaccinipertutti#27]
Ciao @jenkin ,
nel changelog è prevista una variazione per domani:<br>
https://github.com/italia/covid19-opendata-vaccini/blob/master/Changelog.md

Non ho idea se "tocca" il tuo flusso (sono un attimo di corsa)

**Comment by jenkin** [comment]
Grazie della segnalazione, sembra che aggiungano solo delle colonne, quindi non dovrebbe cambiare nulla per noi. Ma tengo d'occhio la situazione, se domani è tutto ok chiudo la issue.

**Comment by jenkin** [comment]
Dati cambiati, funziona tutto, chiudo
