### ISSUE TITLE
Percentuale vaccinati 

### ISSUE THREAD

**Issue by MCilento93** [ondata/vaccinipertutti#28]
Salve,
molto carina l'applicazione sviluppata.

Con i dati menzionati come è possibile calcolare la percentuale di persone completamente vaccinate?
Su [sole 24 ore](https://lab24.ilsole24ore.com/numeri-vaccini-italia-mondo/) la percentuale ad oggi è del 22%, mentre io in via preliminare mesi fa quando iniziò la distribuzione feci il mero rapporto a 2 (2 dosi/persona) e [ricalcolo regionale](https://github.com/MCilento93/italy_coviddata/blob/master/coviddata/italy_coviddata_vaccines.py), ottenendo ad oggi 30%. La differenza più che per il vaccino Jansen è per il discorso delle somministrazione monodose per ex-pazienti covid.

Con i dati open è possibile affinare il calcolo?
Grazie

**Comment by jenkin** [comment]
Ciao @MCilento93 , grazie!

Nei dati ufficiali purtroppo non è mai stato introdotto il concetto di *persona vaccinata*, ma solo di dosi somministrate ([dettagli](https://github.com/italia/covid19-opendata-vaccini/issues/79), ma di issue così ce ne sono diverse). Quindi bisogna ricavare il primo dal secondo, noi prendiamo in considerazione seconde dosi più prime dosi Janssen ([dettagli](https://github.com/ondata/vaccinipertutti#le-stime)). Non consideriamo la questione "singola dose per i guariti" ([pag. 3](https://www.trovanorme.salute.gov.it/norme/renderNormsanPdf?anno=2021&codLeg=79033&parte=1%20&serie=null)) perché non viene rilasciata alcuna informazioni su questo. Ti invito ad aprire una issue nel [repo ufficiale](https://github.com/italia/covid19-opendata-vaccini/issues) e chiedere lumi.

La questione del ricalcolo regionale invece non l'ho capita, cosa intendi?

**Comment by MCilento93** [comment]
Sul sito sole 24h quindi credete che quando calcolano le persone vaccinate non hanno un'altra fonte che aggiunga dei dati sulle persone che non necessitano di una seconda dose pfitzer o altro (per ritenersi completamente vaccinate)? 
Grazie della risposta

**Comment by jenkin** [comment]
Se quel dato non è nel [repo ufficiale](https://github.com/italia/covid19-opendata-vaccini/issues), non ce l'ha nessuno, né noi né il sole24ore. Apri una issue lì, se ti va tagga anche questa issue, interessa anche me.

**Comment by jenkin** [comment]
@MCilento93 qualcuno ha segnalato il problema: https://github.com/italia/covid19-opendata-vaccini/issues/174
