### ISSUE TITLE
Lista regione in ordine alfabetico

### ISSUE THREAD

**Issue by aborruso** [ondata/vaccinipertutti#3]
Al momento non lo è

![image](https://user-images.githubusercontent.com/30607/104700329-46940400-5714-11eb-9e1a-c510210d9e5c.png)

**Comment by nelsonmau** [comment]
taggare come "question" questa issue mi pare spocchioso, piuttosto è un bug e tale tag si meritava!

**Comment by jenkin** [comment]
Fatto
