### ISSUE TITLE
Pulsante (?)

### ISSUE THREAD

**Issue by nelsonmau** [ondata/vaccinipertutti#5]
non si vede, deve aprirsi automaticamente quando l'utente entra ed essere molto più visibile

**Comment by jenkin** [comment]
Però che brutto iniziare con la modale aperta... :(

**Comment by jenkin** [comment]
Ho aggiunto le icone di condivisione, ora quel blocco è molto più visibile. Anche se il pulsante per aprire la modale non è in primissimo piano, la soluzione qui proposta (aprirla al caricamento della pagina) a mio avviso è tremenda per la UX. Sono aperto naturalmente ad altri suggerimenti.
