### ISSUE TITLE
Formattazione testo: allineare a sinistra e qualche a capo

### ISSUE THREAD

**Issue by aborruso** [ondata/vaccinipertutti#7]
Caro @jenkin,
a sembra molto più leggibile, con le frasi chiave "interrotte" con un break.

Una volta che vai a capo però, farei l'allineamento a sinistra.

![image](https://user-images.githubusercontent.com/30607/104920920-d9dd6b80-5998-11eb-8ced-9ca8788c9b5c.png)

**Comment by jenkin** [comment]
Fatto
